### ISSUE TITLE
How does jraph support large scale graph neural network training?

### ISSUE THREAD

**Issue by cfangplus** [deepmind/jraph#18]
HI,

We note that DeepMind team use jraph to win the 2021 KDD OGB MAG240M-LSC Track.
As I found that, this OGB dataset contain 100 million nodes, so I want to say, how does jraph support this large scale gnn model training? The jraph documentation is too simple, could you please provide some more details about the MAG240M-LSC Track and the large scale gnn training? thx.

**Comment by jg8610** [comment]
Hi,

Please take a look the released repository for MAG: 
https://github.com/deepmind/deepmind-research/tree/master/ogb_lsc/mag
