### ISSUE TITLE
Can we have some benchmark test data?

### ISSUE THREAD

**Issue by cfangplus** [deepmind/jraph#21]
Hi,

Did you held some GNN benchmark test on some common datasets like OGB ? Or did you  compared jraph performance with other library such as AWS DGL, PyTorch Geometric? What's the roadmap of jraph? Thx for your attention.

**Comment by ameya98** [comment]
We have a benchmark of jraph on ogbg_molpcba (from the OGB dataset) at https://github.com/google/flax/tree/main/examples/ogbg_molpcba!

**Comment by cfangplus** [comment]
that's great, thx
