### ISSUE TITLE
What's the purpose of empty graph in padding?

### ISSUE THREAD

**Issue by EngineerKhan** [deepmind/jraph#23]
Hi!

I came across the padding function (`pad_with_graphs`) and have a naive question: why do we use an empty graph there?
Also, we specify only the number of edges (and nodes). Which algorithm determines their incidence (i.e. which edge would connect which pair of nodes)? Thanks a lot.

**Comment by jg8610** [comment]
Hey!

Good question - we connect all edges to a single node (the first one) and then all other nodes are disconnected.

We use this because then with `unpad_with_graphs` we know how to remove the padding graph.
