### ISSUE TITLE
Feature engineering methods 

### ISSUE THREAD

**Issue by INF800** [deepmind/jraph#25]
Hi, does this library provide utilities for feature engineering on graphs? For example I may want to calculate different node centrality measures or other metrics that are commonly used in traditional ML. Basically, the question would be - will we have utilities for all the graph related stuff + machine learning or just related to GNNs?

> *jraph provides a data structure for graphs, a set of utilites for working with graphs*

**Comment by jg8610** [comment]
Hey INF800, 

Unfortunately we don't - this is a library for GNNs.

Network X is a nice library for this:

https://networkx.org/documentation/stable/tutorial.html
