### ISSUE TITLE
Doubt about the implementation of GraphConvolution

### ISSUE THREAD

**Issue by llan-ml** [deepmind/jraph#32]
I found that the output of [the GCN implementation in this repo](https://github.com/deepmind/jraph/blob/0d1da095fd02c874587199c46f69e29459a96a2d/jraph/_src/models.py#L562-L585) is different from that of the original matrix multiplication based implementation, when the input graph is not symmetric.

I did some tests in this [colab notebook](https://colab.research.google.com/drive/1A2WLtodRDpNlygxYhkzmbxnIy2ODjwew?usp=sharing). 

@jg8610 Could you take a look at this?

**Comment by jg8610** [comment]
Thanks, I am taking a look.

**Comment by jg8610** [comment]
Hi llan-ml,

I believe the matrix multiple version you are talking about assumes an undirected graph (i.e. a symmetric adjacency matrix), at least according the original paper. Could you point me to the paper with the directed version?

Jonathan

**Comment by llan-ml** [comment]
Hi,

Indeed, the matrix based version assumes that the graph is undirected. For directed graphs, the author suggests to do normalization with $D^{-1}A$ instead of the symmetric normalization ([here](https://github.com/tkipf/gcn/issues/91#issuecomment-469181790) and [here](https://github.com/tkipf/relational-gcn/blob/4bec1341dd46b72bf482f7ed26c2dca4533577f6/rgcn/train.py#L78-L84)).

In addition, even for undirected graphs, I still do not know why we perform pre-normalization by sqrt `sender_degree` to implement $D^{-1/2}AD^{-1/2}X$, though `sender_degree` and `receiver_degree` are the same and the final results are not influenced. Could you please clarify this a bit more?

**Comment by llan-ml** [comment]
I think it is a good idea to document this more clearly. BTW, thanks for making this repo!
