### ISSUE TITLE
Adjacency matrix to GraphsTuple

### ISSUE THREAD

**Issue by salfaris** [deepmind/jraph#36]
I couldn't find any function in the jraph API that allows me to convert an arbitrary adjacency matrix to a GraphsTuple object. I assume we are expected to do this manually?

Just curious if there is any potential future work on this feature? I would be happy to explore something down this road.

**Comment by jg8610** [comment]
Hey Salfaris,

We don't currently have a function that does this, but we would be very happy to receive pull requests :)

**Comment by salfaris** [comment]
Hey, that's great :) 

I already implemented the function, but now wondering how to run the tests?

**Comment by salfaris** [comment]
Update: nevermind I found out how to run the tests :)

**Comment by salfaris** [comment]
@jg8610 PR is merged (many thanks for the support!), so should we close this issue?
