### ISSUE TITLE
Switch from `jax.tree_multimap` to `jax.tree_map`

### ISSUE THREAD

**Issue by marcvanzee** [deepmind/jraph#38]
Jraph is still using `jax.tree_multimap`, which is giving a deprecation warning. This can be problematic for users, for instance for us (Flax), since our CI fails if we hit a deprecation warning. i created an exception for Jraph now, but since `tree_multimap` can be replaced in-place for `tree_map`, this seems like an easy fix!

See https://github.com/google/flax/issues/2037

**Comment by swamidass** [comment]
Note: the conda distribution of jraph still has this problem (v0.0.1). Perhaps update that version? The pip distribution is v0.0.6 and the problem is fixed here.
