### ISSUE TITLE
[🐛 Bug] Experiencing a website timeout for https://jraph.readthedocs.io/en/latest/.

### ISSUE THREAD

**Issue by dynamicwebpaige** [deepmind/jraph#39]
### Expected behavior

The link to [`jraph`'s documentation](https://jraph.readthedocs.io/en/latest/) should take me to a Read the Docs website.

### Experienced behavior

Unfortunately, am bouncing between a timeout and an HTML-only formatted version of the docs. 😞

<img width="804" alt="Screen Shot 2022-06-20 at 11 44 55 PM" src="https://user-images.githubusercontent.com/3712347/174733983-cbfba509-0cb9-45ab-aa33-0910c1469e30.png">

<img width="800" alt="Screen Shot 2022-06-20 at 11 43 43 PM" src="https://user-images.githubusercontent.com/3712347/174733872-81c8e3b2-6a65-4542-b3ae-1c644631c810.png">

**Comment by jg8610** [comment]
Hey Paige,

I am not able to replicate this - would you be able to check again now?
