### ISSUE TITLE
Jraph Flax incorporation

### ISSUE THREAD

**Issue by GrantMcConachie** [deepmind/jraph#49]
Hi! I saw on the Haiku repo that they are urging people to move to flax, and was just  wondering if jraph has any intention of moving to a flax framework? 

Thanks!

**Comment by thomaskeck** [comment]
jraph is independent of haiku. So you can already use jraph with flax (or any other jax-based ML library)
Only the examples depend on haiku. There are no plans currently to update the examples.

**Comment by GrantMcConachie** [comment]
If I wrote some examples in flax do you think it would be useful to have on here?
